from .multi_lora_loader import NODE_CLASS_MAPPINGS as MULTI_LORA_LOADER_NODE_CLASS_MAPPINGS
from .multi_lora_loader import NODE_DISPLAY_NAME_MAPPINGS as MULTI_LORA_LOADER_NODE_DISPLAY_NAME_MAPPINGS
from .multi_trigger_loader import NODE_CLASS_MAPPINGS as MULTI_TRIGGER_LOADER_NODE_CLASS_MAPPINGS
from .multi_trigger_loader import NODE_DISPLAY_NAME_MAPPINGS as MULTI_TRIGGER_LOADER_NODE_DISPLAY_NAME_MAPPINGS
from .multi_loraname_loader import NODE_CLASS_MAPPINGS as MULTI_LORANAME_LOADER_NODE_CLASS_MAPPINGS
from .multi_loraname_loader import NODE_DISPLAY_NAME_MAPPINGS as MULTI_LORANAME_LOADER_NODE_DISPLAY_NAME_MAPPINGS
from .lora_adapter import NODE_CLASS_MAPPINGS as LORA_ADAPTER_NODE_CLASS_MAPPINGS
from .lora_adapter import NODE_DISPLAY_NAME_MAPPINGS as LORA_ADAPTER_NODE_DISPLAY_NAME_MAPPINGS
from .dynamic_lora_loader import NODE_CLASS_MAPPINGS as DYNAMIC_LORA_LOADER_NODE_CLASS_MAPPINGS
from .dynamic_lora_loader import NODE_DISPLAY_NAME_MAPPINGS as DYNAMIC_LORA_LOADER_NODE_DISPLAY_NAME_MAPPINGS
from .image_batch_to_list import NODE_CLASS_MAPPINGS as IMAGE_BATCH_TO_LIST_NODE_CLASS_MAPPINGS
from .image_batch_to_list import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_BATCH_TO_LIST_NODE_DISPLAY_NAME_MAPPINGS
from .convert_greyscale import NODE_CLASS_MAPPINGS as CONVERT_GREYSCALE_NODE_CLASS_MAPPINGS
from .convert_greyscale import NODE_DISPLAY_NAME_MAPPINGS as CONVERT_GREYSCALE_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **MULTI_LORA_LOADER_NODE_CLASS_MAPPINGS,
    **MULTI_TRIGGER_LOADER_NODE_CLASS_MAPPINGS,
    **MULTI_LORANAME_LOADER_NODE_CLASS_MAPPINGS,
    **LORA_ADAPTER_NODE_CLASS_MAPPINGS,
    **DYNAMIC_LORA_LOADER_NODE_CLASS_MAPPINGS,
    **IMAGE_BATCH_TO_LIST_NODE_CLASS_MAPPINGS,
    **CONVERT_GREYSCALE_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MULTI_LORA_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **MULTI_TRIGGER_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **MULTI_LORANAME_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **LORA_ADAPTER_NODE_DISPLAY_NAME_MAPPINGS,
    **DYNAMIC_LORA_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_BATCH_TO_LIST_NODE_DISPLAY_NAME_MAPPINGS,
    **CONVERT_GREYSCALE_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']